name: ExecuÃ§Ã£o de Testes no Service

on:
  repository_dispatch:
    types: [trigger-workflow] # Deve corresponder ao 'event_type' enviado pelo dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # NecessÃ¡rio para ler o repositÃ³rio
      checks: write       # NecessÃ¡rio para o dorny/test-reporter funcionar corretamente

    steps:
      - name: Exibir dados recebidos
        run: |
          echo "ServiÃ§o: ${{ github.event.client_payload.service }}"
          echo "VersÃ£o: ${{ github.event.client_payload.version }}"
          echo "Ambiente: ${{ github.event.client_payload.ambiente }}"
          echo "Tenant: ${{ github.event.client_payload.tenant }}"

      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar DependÃªncias
        run: |
          npm install -g @hoppscotch/cli junit-viewer

      - name: Configurar VariÃ¡veis Globais Dinamicamente
        env:
          AMBIENTE: ${{ github.event.client_payload.ambiente }}   # Quando for pelo trigger-workflow, a variÃ¡vel AMBIENTE Ã© passada atravÃ©s do client_payload
          TENANT: ${{ github.event.client_payload.tenant }}   # Quando for pelo trigger-workflow, a variÃ¡vel AMBIENTE Ã© passada atravÃ©s do client_payload
        run: |
          if [ "$AMBIENTE" == "HML" ]; then
              BASE_URL="https://api.trello.com/"
          elif [ "$AMBIENTE" == "DEV" ]; then
              BASE_URL="https://dev.hml.api.trello.com/"
          elif [ "$AMBIENTE" == "TRN" ]; then
              BASE_URL="https://trn.hml.api.trello.com/"
          else
              echo "Ambiente invÃ¡lido: $AMBIENTE"
              exit 1
          fi

          if [ "$TENANT" == "EUD" ]; then
              TENANT="EUD"
          elif [ "$TENANT" == "BOT" ]; then
              TENANT="BOT"
          else
              echo "Tenant invÃ¡lido ou nÃ£o configurado: $TENANT"
              exit 1
          fi

          jq --arg url "$BASE_URL" --arg tenant "$TENANT" '
            .variables |= map(
              if .key == "baseUrl" then
                .initialValue = $url
              elif .key == "tenant" then
                .initialValue = $tenant
              else
                .
              end
            )
          ' scripts-hoppscotch/environments/Global.json > scripts-hoppscotch/environments/Global-temp.json && mv scripts-hoppscotch/environments/Global-temp.json scripts-hoppscotch/environments/Global.json
      
      - name: Executar testes de API
        run: |
          mkdir -p results
          hopp test \
            -e scripts-hoppscotch/environments/Global.json \
            -d 1000 scripts-hoppscotch/collections/testes_api.json \
            --reporter-junit results/report.xml || true

      - name: Gerar relatÃ³rio HTML
        if: always()
        run: |
          junit-viewer \
            --results=results/report.xml \
            --save=results/relatorio.html \
            --relativePath=true

      - name: Publicar artefato do relatÃ³rio HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-hoppscotch
          path: results/relatorio.html

      - name: Publicar resultado dos testes no Summary
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: ðŸ“Š RelatÃ³rio de Testes de API
          path: results/report.xml
          reporter: java-junit
          fail-on-error: false